
import Header from '@/components/Header'
import './globals.css'
import { Inter, Mulish } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body className={inter.className}>     
        <Header></Header>
        {children}
        
        <Footer></Footer>
        </body>
    </html>
  )
}
